---
driver:
  name: terraform

provisioner:
  name: terraform
  variables:
    - region=us-west-2

platforms:
  - name: ubuntu

transport:
  name: ssh
  ssh_key: /tmp/erwin_us-west-2.pem

verifier:
  name: terraform
  format: doc
  groups:
    - name: default
      controls:
        - operating_system
        - open_ports
        - internet_access
      hostnames: public_dns
      username: ubuntu

suites:
  - name: default
